### ISSUE TITLE
`exec` redirection broken when jimtcl is called with closed stdin

### ISSUE THREAD

**Issue by gravicappa** [msteveb/jimtcl#201]
In Jimtcl v0.80

Create simple script that employs exec with redirection
```
$ printf 'exec wc -l < [info script]\n` > io.tcl
```

Works when executed in a terminal
```
$ jimtcl io.tcl
```

Breaks when called with closed stdin
``` 
$ jimtcl io.tcl 0<&-
io.tcl:1: Error: 0
wc: 'standard input': Bad file descriptor
wc: -: Bad file descriptor
at file "io.tcl", line 1
```

Expected behaviour: works as usual.

**Comment by msteveb** [comment]
Interesting. So the problem is here:

```
            if (inputId != -1) {
                dup2(inputId, fileno(stdin));
                close(inputId);
            }
```

If stdin is closed, inputId ends up as 0 and fileno(stdin) is also 0, so dup2() does nothing and then it is closed. We could fix this by checking for inputId != fileno(stdin), but could there be other weird situations when one or more standard file descriptors is closed?
