### ISSUE TITLE
Issues with jimsh output.

### ISSUE THREAD

**Issue by geoff1111** [msteveb/jimtcl#328]
The output of `jimsh` `puts` command differs markedly from `tclsh` in certain situations, which may indicate a bug in `jimsh`. Compare the output from `jimsh` and `tclsh`:

```
Welcome to Jim version 0.82
. puts -nonewline
-nonewline
. puts -nonewline -nonewline
. puts -nonewline hi
. puts -nonewline hi\n
-nonewlinehihi
.
```

```
% puts -nonewline
-nonewline
% puts -nonewline -nonewline
-nonewline% puts -nonewline hi
hi% puts -nonewline hi\n
hi
%
```

**Comment by msteveb** [comment]
So this is because jimsh is buffering stdout and you only see it once it is flushed.
We could fix it by flushing stdout after each interactive command, but it wouldn't do much good, because of the way linenoise line editing works, the output would be overwritten by the prompt. This works fine in a non-interactive script, so I don't think there is much point in changing the behaviour.

**Comment by geoff1111** [comment]
Thanks for the explanation (and also the great work on JimTcl!)

**Comment by msteveb** [comment]
You're welcome
