### ISSUE TITLE
Different results from "info exists" with "set" in namespace

### ISSUE THREAD

**Issue by sgbeal** [msteveb/jimtcl#329]
This may or may not be a bug but i just randomly stumbled over it while experimenting with namespaces so will pass it on:

Input script:

```tcl
namespace eval xyz {
  set x "a b c"
  puts "x=$x"
}
puts "::x? [info exists ::x]"
puts "::xyz::x? [info exists ::xyz::x]"
```

Output with jimsh then tclsh:

```console
$ jimsh foo.tcl
x=a b c
::x? 0
::xyz::x? 0

$ tclsh foo.tcl
x=a b c
::x? 0
::xyz::x? 1
```

Sidebar: my hope here was to get a locally-scoped var which disappears at the end of `namespace eval`. jimsh does exactly what i'd hoped but tclsh has other intentions.

Interestingly, both impls agree that "set" from outside the `namespace eval` creates a persistent var:

```tcl
set ::xyz::abc 1
puts [info exists ::xyz::abc]
```

emits "1" for both tclsh and jimsh.

Both impls (unsurprisingly) behave identically with `variable`-defined vars, as opposed to `set`-defined vars.

This is very possibly not a bug, just pointing out the discrepancy.

**Comment by msteveb** [comment]
Yes, this is "as designed". Here is an excerpt from README.namespaces that explains it.

Variable resolution
-------------------
The variable command in Jim Tcl has the same syntax as Tcl, but is closer in behaviour to the global command.
The variable command creates a link from a local variable to a namespace variable, possibly initialising it.

For example, the following procedure uses 'variable' to initialise and access myvar.

proc ::test::myproc {} {
  variable myvar 4
  incr myvar
}

Note that there is no automatic resolution of namespace variables.
For example, the following will *not* work.

namespace eval ::test {
  variable myvar 4
}
namespace eval ::test {
  # This will increment a local variable, not ::test::myvar
  incr myvar
}

And similarly, the following will only access local variables

set x 3
namespace eval ::test {
	# This will increment a local variable, not ::x
	incr x
	# This will also increment a local variable
	incr abc::def
}

In the same way that variable resolution does not "fall back" to
global variables, it also does not "fall back" to namespace variables.

This approach allows name resolution to be simpler and more efficient
since it uses the same variable linking mechanism as upvar/global
and it allows namespaces to be implicit. It also solves the "creative
writing" problem where a variable may be created in an unintentional
scope.
