### ISSUE TITLE
Implement file normalize for systems without realpath()

### ISSUE THREAD

**Issue by kflu** [msteveb/jimtcl#91]
MinGW built jimsh have a non-implemented `file normalize`. The reason is that [MinGW doesn't have `realpath()` function.](https://sourceforge.net/p/mingw/bugs/2207/). It would be nice to implement file normalize for systems without `realpath`. `file normalize` is such an important command that it deserves an implementation that works widely:)

**Comment by msteveb** [comment]
I agree it would be nice to have, but it requires someone to implement realpath(), which is non-trivial.

I will accept a patch...

**Comment by mardukbp** [comment]
I think that [dirent](https://github.com/tronkko/dirent) provides the full path.

**Comment by msteveb** [comment]
It doesn't. I will accept a working patch.

**Comment by tangentsoft** [comment]
Meanwhile, [the docs](http://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html#_file) should warn that `file normalize` may give a "Not implemented" error in this case. There may be other cases where a documented command won't actually be built into Jim; those should be documented as well.

This particular case happens in `autosetup` where `jimsh0` is built without first trying to discover whether `realpath` exists, presumably because that would be rather meta: a platform-independent build system needing to make platform checks in order to build a tool provided in order to avoid a platform dependency. :)

(And yes, I know about autosetup's `file-normalize` proc, presumably added to work around this very problem.)

**Comment by msteveb** [comment]
It's true that there are many command that either won't be implemented, or may have a cut-down implementation based on selected features and the capabilities of the platform and compiler. I think that adding this information to the docs would be: incomplete, wrong most of the time, burdensome to maintain and get in the way of the the main content of the docs.

It may be useful to maintain this information separately, but this is still going to be a reasonable amount of work to implement and maintain. Contributions welcome.

**Comment by tangentsoft** [comment]
> incomplete, wrong, burdensome ...

Granted, but the current situation is that the Jim manual says it supports feature X, you try to use feature X, and it fails for no obvious reason.

Or the reverse: you're looking at Tcl docs, it tells you about `file normalize` or something else that's only conditionally supported by Jim, so you try it and it says something unhelpful like "Not implemented." Then you go to the Jim docs to verify that the function doesn't exist, only to find that it says it does exist, without any caveats or conditions.

Either way, the only way to figure out how on your own is to go spelunking through the code, or hope to dig up some previous posting about it on the web somewhere.

> Contributions welcome.

I'll add it to the list. I'm in the middle of several projects on Fossil itself at the moment, and I shouldn't allow myself to be distracted.

I'd prefer to make these documentation improvements via Fossil. If you're willing to give me a developer login, you can email me a default password via my profile's email address, which I'll change to something strong and random after first login. I'd prefer either "tangent" or "wyoung" as a login name.
