### ISSUE TITLE
if 1 {puts "}$"};  if 1 { puts "}$" }

### ISSUE THREAD

**Issue by tcler** [msteveb/jimtcl#99]
[jianhong@dhcp-12-125 ~]$ jimsh 
Welcome to Jim version 0.77
. puts "}$"
}$
. if 1 { puts "}$" } else { puts x }
$
. if 1 { puts "\}$" } else { puts x }
}$

**Comment by tcler** [comment]
[jianhong@dhcp-12-125 ~]$ jimsh 
Welcome to Jim version 0.77
. if 1 {puts "}$"}
$}
. if 1 { puts "}$" }
$
. exit

[jianhong@dhcp-12-125 ~]$ tclsh
% if 1 {puts "}$"}
extra characters after close-brace
% if 1 { puts "}$" }
extra characters after close-brace

**Comment by msteveb** [comment]
Jim Tcl is quite permissive when parsing scripts, but this can lead to odd behaviour such as this.

I could make it somewhat more strict, thus giving an error in these cases.
But this would then mean tests such as this would fail (because the same parser is used by subst):

```
test subst-10.5 {break in a subst, parse error} {
    subst {foo [break ;set bar baz ;set a {}{} ; stuff] bar}
} {foo }

```

Personally I'm fine with that.

**Comment by msteveb** [comment]
Done

**Comment by tcler** [comment]
Got it. Thank you for explaining
